# -*- coding: utf-8 -*-
"""test.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TtNcC0Z_QoYtHIJ7ym4HhAW3svoof4Ig
"""

import streamlit as st

# --- 1. Set Page Configuration (Optional, but good practice) ---
st.set_page_config(
    page_title="مساعد التحية البسيط", # Page title in browser tab
    page_icon="👋",                  # Favicon
    layout="centered"                # Page layout
)

# --- 2. Display the App Title and Introduction ---
st.title("مساعد التحية البسيط 👋")
st.markdown("اختر تحية وسأرد عليها.")

# --- 3. Create Options for the User ---
# Using a selectbox to allow the user to choose an option.
# The selected_greeting variable will hold the user's choice.
selected_greeting = st.selectbox(
    "ماذا تود أن تقول؟", # Label for the selectbox
    ("اختر تحية...", "قل مرحباً", "قل أهلاً"), # Options for the user
    index=0 # Default selected option
)

# --- 4. Logic to Respond Based on User's Choice ---
# An if-elif-else structure to check the selected option and provide a response.
if selected_greeting == "قل مرحباً":
    # st.write() is used to display text in Streamlit.
    st.write("مرحباً!")
elif selected_greeting == "قل أهلاً":
    st.write("أهلاً بك!")
elif selected_greeting == "اختر تحية...":
    st.info("الرجاء اختيار تحية من القائمة أعلاه.") # Provide a hint if default is selected

# --- Optional: Add a footer or other elements ---
st.markdown("---")
st.caption("مساعد بسيط تم إنشاؤه باستخدام Streamlit.")